version: "3.8"
services:
  my_flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./configuration/sample.env 
    ports:
      - "5000:5000"  
    expose:
      - "5000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - my_flask_app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge