name: python_flask_helm_flux

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PAT }}
        
    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: python_flask_helm_flux
        file: python_flask_helm_flux/Dockerfile
        push: true
        tags: docker.io/198404/python_flask_helm_flux:0.0.1
        
